#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 NAGAKI Yuki
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
item = 0

for line in sys.stdin:
    ans += float(line)
    item += 1

print(ans / item)
